---
- hosts: webservers
  gather_facts: false
  tasks:
    - name: Docker login
      docker_login:
        username: ansarikaleem
        password: 233844

    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: "/opt/docker"
        name: docker.io/ansarikaleem/abctechnologies
        push: true
        source: build
      register: out

    - debug:
        var: out

    - name: Start a container
      community.docker.docker_container:
        name: abctechnologies
        image: ansarikaleem/abctechnologies
        state: started
        ports:
          - 8090:8080
      register: out

    - debug:
        var: out
